// Run with Node 18+: node tests/model.test.mjs
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const source = await fs.readFile(new URL('../assets/model.js', import.meta.url), 'utf8');
const { validateData, readState, writeState, selectResources, safeMaterialURL, labels } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const data = validateData(JSON.parse(await fs.readFile(new URL('../data/resources.json', import.meta.url), 'utf8')));
const { resources, taxonomy } = data;
const selected = query => selectResources(resources, readState(query, taxonomy), taxonomy);
assert.equal(resources.length, 15);
assert.ok(resources.every(r => r.isSample && r.materials.every(m => m.isPlaceholder && m.url === null)));
for (const key of Object.keys(taxonomy)) for (const value of Object.keys(taxonomy[key])) assert.ok(resources.some(r => r[key].includes(value)));
assert.equal(selected('').length, 15);
assert.equal(selected('topics=mathematics&languages=spanish').length, 4);
assert.equal(selected('languages=english&languages=spanish').length, 15);
assert.deepEqual(selected('audiences=families&audiences=researchers').map(r => r.id).sort(), resources.filter(r => r.audiences.includes('families') || r.audiences.includes('researchers')).map(r => r.id).sort());
assert.equal(selected('q=%20CoUnTiNg%20SPANISH%20').length, 1);
assert.equal(selected('q=zzzznothing').length, 0);
assert.deepEqual(selected('sort=desc').map(r => r.id), selected('').map(r => r.id).reverse());
assert.equal(selected('topics=unknown&sort=unknown').length, 15);
const state = readState('q=Sample&topics=mathematics&topics=literacy&languages=spanish&sort=desc', taxonomy);
assert.deepEqual(readState(writeState(state), taxonomy), state);
assert.equal(labels({}, 'topics', taxonomy), 'Not specified');
assert.doesNotThrow(() => validateData({taxonomy, resources: [{...resources[0], topics: null, materials: null}]}));
assert.throws(() => validateData({taxonomy, resources: [resources[0], resources[0]]}));
assert.throws(() => validateData({taxonomy, resources: [{...resources[0], topics: ['unknown']}]}));
for (const url of ['javascript:alert(1)', 'data:text/html,x', '//example.com', '/absolute', 'java\nscript:alert(1)']) assert.equal(safeMaterialURL(url), null);
assert.equal(safeMaterialURL('materials/activity.pdf'), 'materials/activity.pdf');
assert.equal(safeMaterialURL('https://example.com/material.pdf'), 'https://example.com/material.pdf');
console.log('PASS: data coverage, sample safeguards, OR/AND filtering, search, sorting, URL round trip, missing metadata, validation, and URL safety.');
